services:
  db:
    image: postgres:15
    container_name: tg-chat-db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
